Table branches{
  branch_id int [pk, increment]
  name varchar(100) [not null, unique]
  location varchar(50)
  created_at timestamp [default: 'now()']
}

Table trainers{
  trainer_id int [pk, increment]
  first_name varchar(50) [not null]
  last_name varchar(50) [not null]
  email varchar(100) [not null, unique]
  phone_number varchar(20)
  date_of_birth date
  hire_date date [default: 'now()']
  salary decimal(10, 2)
  branch_id int [not null, ref: > branches.branch_id]
  created_at timestamp [default: 'now()']
}

Table members{
  member_id int [pk, increment]
  first_name varchar(50) [not null]
  last_name varchar(50) [not null]
  email varchar(100) [not null, unique]
  phone_number varchar(20)
  date_of_birth date
  enrollment_date date [default: 'now()']
  branch_id int [not null, ref: > branches.branch_id]
  is_active boolean [default: true]
  created_at timestamp [default: 'now()']
}

Table program_types{
  program_id int [pk, increment]
  name varchar(50) [not null, unique]
  description text 
  created_at timestamp [default: 'now()']
}

Table classes{
  class_id int [pk, increment]
  name varchar(50) [not null, unique]
  scheduled_date date [not null]
  start_time time [not null]
  capacity int [default: 20] 
  program_id int [not null, ref: > program_types.program_id]
  trainer_id int [not null, ref: > trainers.trainer_id]
  created_at timestamp [default: 'now()']
}

Table bookings{
  booking_id int [pk, increment]
  member_id int [not null, ref: > members.member_id]
  class_id int [not null, ref: > classes.class_id]
  booking_date date [default: 'now()']
  created_at timestamp [default: 'now()']

  indexes {
    (member_id, class_id) [unique]
  }
}

Table membership_plans{
  plan_id int [pk, increment]
  name varchar(50) [not null, unique]
  price decimal(10,2) [not null]
  duration_months int [not null]
  created_at timestamp [default: 'now()']
}

Table payment{
  payment_id int [pk, increment]
  member_id int [not null, ref: > members.member_id]
  plan_id int [not null, ref: > membership_plans.plan_id]
  amount decimal(10,2) [not null]
  payment_method varchar(30)
  payment_date timestamp [default: 'now()']
  status varchar(20)
  created_at timestamp [default: 'now()']
}

Table waitlist{
  waitlist_id int [pk, increment]
  class_id int [not null, ref: > classes.class_id]
  member_id int [not null, ref: > members.member_id]
  joined_at timestamp [default: 'now()']
  status varchar(20) [default: 'Waiting']
  created_at timestamp [default: 'now()']
  
  indexes {
    (member_id, class_id) [unique]
  }
}