Table publishers{
    publisher_id int [pk, increment]
    name varchar(100) [not null, unique]
    location varchar(50)
    created_at timestamp [default: 'now()']
}

Table authors{
    author_id int [pk, increment]
    first_name varchar(50) [not null]
    last_name varchar(50) [not null]
    email varchar(100) [not null, unique]
    phone_number varchar(20)
    date_of_birth date
    created_at timestamp [default: 'now()']
}

Table books{
    book_id int [pk, increment]
    book_name varchar(50) [not null]
    publisher_id int [not null, ref: > publishers.publisher_id]
    edition varchar(30)
    isbn varchar(13) [unique]
    cost decimal(10, 2) [not null]
    publish_date date [default: 'now()']
    stock_quantity int [not null] 
    created_at timestamp [default: 'now()']
}

Table book_authors{
    book_id int [not null, ref: > books.book_id]
    author_id int [not null, ref: > authors.author_id]
    created_at timestamp [default: 'now()']

    indexes {
        (book_id, author_id) [pk, unique]
    }
}

Table customers{
    customer_id int [pk, increment]
    first_name varchar(50) [not null]
    last_name varchar(50) [not null]
    email varchar(100) [not null, unique]
    phone_number varchar(20)
    date_of_birth date
    created_at timestamp [default: 'now()']
}


Table orders{
    order_id int [pk, increment]
    customer_id int [not null, ref: > customers.customer_id] 
    order_date date [default: 'now()']
    order_status varchar(30)
    created_at timestamp [default: 'now()']
}


Table order_items{
    order_item_id int [pk, increment]
    order_id int [not null, ref: > orders.order_id]
    book_id int [not null, ref: > books.book_id]
    quantity int [not null]
    price  decimal(10, 2) [not null] 
    created_at timestamp [default: 'now()']

    indexes {
        (order_id, book_id) [unique]
    }
}