CREATE TABLE membership_plans(
  plan_id SERIAL PRIMARY KEY,
  name VARCHAR(50) UNIQUE NOT NULL,
  price NUMERIC(10,2) NOT NULL,
  duration_months INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);